## Generated by SimInf (v5.0.0) 2017-09-21 13:25 */

##' Class \code{SICR}
##'
##' Class to handle the \code{SICR} \code{SimInf_model}.
##' @export
setClass("SICR", contains = "SimInf_model")

##' Create a model for the SimInf framework
##'
##' Create a model to be used by the SimInf framework.
##' @param u0 A data.frame with the initial state in each node.
##' @param tspan A vector (length >= 2) of increasing time points
##'     where the state of each node is to be returned.
##' @import SimInf
##' @import methods
##' @export
##' @examples
##' ## Please add example(s) how to use the model
SICR <- function(u0, 
                 tspan,
                 events    = NULL,
                 phi       = NULL,
                 upsilon_c = NULL,
                 upsilon_y = NULL,
                 upsilon_a = NULL,
                 gamma_c   = NULL,
                 gamma_y   = NULL,
                 gamma_a   = NULL,
                 chi_c   = NULL,
                 chi_y   = NULL,
                 chi_a   = NULL,
                 rho_c   = NULL,
                 rho_y   = NULL,
                 rho_a   = NULL,
                 psi_c = NULL,
                 psi_y = NULL,
                 psi_a = NULL,
                 alpha_c   = NULL,
                 alpha_y   = NULL,
                 alpha_a   = NULL,
                 sigma     = NULL,
                 beta_t1   = NULL,
                 beta_t2   = NULL,
                 beta_t3   = NULL,
                 beta_t4   = NULL,
                 end_t1    = NULL,
                 end_t2    = NULL,
                 end_t3    = NULL,
                 end_t4    = NULL,
                 distance  = NULL,
                 coupling  = NULL) 
{
    compartments <- c("Sc", "Ic", "Cc", "Rc", 
                      "Sy", "Iy", "Cy", "Ry", 
                      "Sa", "Ia", "Ca", "Ra")

    ## Check u0
    if (!is.data.frame(u0))
        u0 <- as.data.frame(u0)
    if (!all(compartments %in% names(u0)))
        stop("Missing columns in u0")
    u0 <- u0[, compartments, drop = FALSE]

    G <- new("dgCMatrix"
        , i = c(0L, 3L, 6L, 1L, 4L, 7L, 2L, 5L, 8L, 3L, 6L, 9L, 4L, 7L, 10L, 
                5L, 8L, 11L, 3L, 6L, 12L, 4L, 7L, 13L, 5L, 8L, 14L, 9L, 12L, 
                10L, 13L, 11L, 14L, 0L, 12L, 1L, 13L, 2L, 14L)
        , p = c(0L, 3L, 6L, 9L, 12L, 15L, 18L, 21L, 24L, 27L, 29L, 31L, 33L, 
                35L, 37L, 39L)
        , Dim = c(15L, 15L)
        , Dimnames = list(c("Sc -> Ic", "Sy -> Iy", "Sa -> Ia", "Ic -> Cc", "Iy -> Cy", 
                            "Ia -> Ca", "Ic -> Rc", "Iy -> Ry", "Ia -> Ra", "Cc -> Rc", 
                            "Cy -> Ry", "Ca -> Ra", "Rc -> Sc", "Ry -> Sy", "Ra -> Sa"), 
                          c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11",
                            "12", "13", "14", "15"))
        , x = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
        , factors = list()
    )

    S <- new("dgCMatrix"
        , i = c(0L, 1L, 4L, 5L, 8L, 9L, 1L, 2L, 5L, 6L, 9L, 10L, 1L, 3L, 5L, 
                7L, 9L, 11L, 2L, 3L, 6L, 7L, 10L, 11L, 0L, 3L, 4L, 7L, 8L, 11L
    )
        , p = c(0L, 2L, 4L, 6L, 8L, 10L, 12L, 14L, 16L, 18L, 20L, 22L, 24L, 
               26L, 28L, 30L)
        , Dim = c(12L, 15L)
        , Dimnames = list(c("Sc", "Ic", "Cc", "Rc", "Sy", "Iy", "Cy", "Ry", "Sa", 
                            "Ia", "Ca", "Ra"),
                          c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
                            "11", "12", "13", "14", "15"))
        , x = c(-1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 
                 1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1)
        , factors = list()
    )

# E is the matrix handling the events
    
    #                 EVENTS by AGE
    #               AGE     
    # AGE group:  C  Y  A    # COMPARTMENTS
    E <- Matrix(c(1, 0, 0,   # Sc
                  1, 0, 0,   # Ic
                  1, 0, 0,   # Cc               
                  1, 0, 0,   # Rc                
                  
                  0, 1, 0,   # Sy
                  0, 1, 0,   # Iy
                  0, 1, 0,   # Cy
                  0, 1, 0,   # Ry
                  
                  0, 0, 1,   # Sa
                  0, 0, 1,   # Ia
                  0, 0, 1,   # Ca
                  0, 0, 1),  # Ra                
                nrow=12,
                ncol=3,
                byrow=TRUE,
                sparse=TRUE)
    E <- methods::as(E, "dgCMatrix")
    colnames(E) <- as.character(1:3)
    rownames(E) <- compartments
    
    
    N <- matrix(c(4, 0,
                  4, 0,
                  4, 0,
                  4, 0,
                  0, 4,
                  0, 4,
                  0, 4,
                  0, 4,
                  0, 0,
                  0, 0,
                  0, 0,
                  0, 0),
                nrow   = 12,
                ncol   = 2,
                byrow  = TRUE)
    colnames(N) <- as.character(1:2)
    rownames(N) <- compartments

    ## Check initial infectious pressure
    if (is.null(phi))
      phi <- rep(0, nrow(u0))
    
    v0 <- matrix(as.numeric(phi), nrow  = 1, byrow = TRUE,
                 dimnames = list("phi"))
    
    storage.mode(v0) <- "double"
    
    ldata <- matrix(c(coupling, end_t1, end_t2, end_t3, end_t4),
                    nrow  = 5,
                    byrow = TRUE)
    storage.mode(ldata) <- "double"
    ldata <- .Call("SimInf_ldata_sp", ldata, distance, 1L, PACKAGE = "SimInf")
    
    gdata <- c(upsilon_c, upsilon_y, upsilon_a,
               gamma_c, gamma_y, gamma_a,
               chi_c, chi_y, chi_a, 
               rho_c, rho_y, rho_a,
               psi_c, psi_y, psi_a,
               alpha_c, alpha_y, alpha_a, sigma,
               beta_t1, beta_t2, beta_t3, beta_t4)
    storage.mode(gdata) <- "double"
    names(gdata) <- c("upsilon_c", "upsilon_y", "upsilon_a",
                      "gamma_c", "gamma_y", "gamma_a",
                      "chi_c", "chi_y", "chi_a", 
                      "rho_c", "rho_y", "rho_a",
                      "psi_c", "psi_y", "psi_a",
                      "alpha_c", "alpha_y", "alpha_a", "sigma",
                      "beta_t1", "beta_t2", "beta_t3", "beta_t4")
    
    model <- SimInf_model(G      = G,
                          S      = S,
                          E      = E,
                          N      = N,
                          tspan  = tspan,
                          events = events,
                          ldata  = ldata,
                          gdata  = gdata,
                          u0     = u0,
                          v0     = v0)
    
    methods::as(model, "SICR")
}

##' Run the model
##'
##' @rdname run-methods
##' @param model The model to run.
##' @param threads Number of threads. Default is NULL, i.e. to use all
##'     available processors.
##' @param solver Which numerical solver to utilize. Default is NULL
##'     i.e., use the default numerical solver in SimInf.
##' @return model with result from simulation.
##' @export
##' @useDynLib SICR, .registration=TRUE
setMethod("run",
    signature(model = "SICR"),
    function(model, threads = NULL, solver = NULL)
    {
        methods::validObject(model)
       .Call(SimInf_model_run, model, threads, solver, PACKAGE = "SICR")
    })

