/* Generated by SimInf (v5.0.0) 2017-09-21 13:25 */

#include <R_ext/Visibility.h>
#include <R_ext/Rdynload.h>
#include "SimInf.h"
#include "SICR.h"


double trFun1(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Sc]*gdata[UPSILON_C]*v[PHI];
}

double trFun2(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Sy]*gdata[UPSILON_Y]*v[PHI];
}

double trFun3(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Sa]*gdata[UPSILON_A]*v[PHI];
}

double trFun4(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Ic]*gdata[CHI_C]*gdata[GAMMA_C];
}

double trFun5(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Iy]*gdata[CHI_Y]*gdata[GAMMA_Y];
}

double trFun6(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Ia]*gdata[CHI_A]*gdata[GAMMA_A];
}

double trFun7(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Ic]*(1.0-gdata[CHI_C])*gdata[GAMMA_C];
}

double trFun8(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Iy]*(1.0-gdata[CHI_Y])*gdata[GAMMA_Y];
}

double trFun9(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Ia]*(1.0-gdata[CHI_A])*gdata[GAMMA_A];
}

double trFun10(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Cc]*gdata[RHO_C];
}

double trFun11(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Cy]*gdata[RHO_Y];
}

double trFun12(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Ca]*gdata[RHO_A];
}

double trFun13(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Rc]*gdata[PSI_C];
}

double trFun14(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Ry]*gdata[PSI_Y];
}

double trFun15(
    const int *u,
    const double *v,
    const double *ldata,
    const double *gdata,
    double t)
{
    return u[Ra]*gdata[PSI_A];
}



SEXP SimInf_model_run(SEXP model, SEXP threads, SEXP solver)
{
    TRFun tr_fun[] = {&trFun1, &trFun2, &trFun3, &trFun4, &trFun5, &trFun6, &trFun7, &trFun8, &trFun9, &trFun10, &trFun11, &trFun12, &trFun13, &trFun14, &trFun15};
    DL_FUNC SimInf_run = R_GetCCallable("SimInf", "SimInf_run");
    return SimInf_run(model, threads, solver, tr_fun, &ptsFun);
}

static const R_CallMethodDef callMethods[] =
{
    {"SimInf_model_run", (DL_FUNC)&SimInf_model_run, 3},
    {NULL, NULL, 0}
};

void attribute_visible R_init_SICR(DllInfo *info)
{
    R_registerRoutines(info, NULL, callMethods, NULL, NULL);
    R_useDynamicSymbols(info, FALSE);
    R_forceSymbols(info, TRUE);
}

